version: '3'

vars:
  # Input/Output directories
  IMAGE_PATH: "{{if .IMAGE_PATH}}{{.IMAGE_PATH}}{{else}}{{.ROOT_DIR}}/frames{{end}}"
  VIDEO: "{{.VIDEO}}"
  # Fix: Ensure PARENT_DIR is calculated correctly from VIDEO or IMAGE_PATH
  PARENT_DIR: 
    sh: |
      if [ -n "{{.VIDEO}}" ]; then echo $(dirname "{{.VIDEO}}"); else echo $(dirname "{{.IMAGE_PATH}}"); fi
  OUTPUT_DIR: "{{.PARENT_DIR}}/gaussian-splat-generation"
  DISTORTED_DIR: "{{.OUTPUT_DIR}}/distorted"
  SPARSE_DIR: "{{.OUTPUT_DIR}}/sparse_initial" # Renamed to avoid collision with undistorted output
  SPARSE_ZERO_DIR: "{{.SPARSE_DIR}}/0"
  SPARSE_ZERO_REFINED_DIR: "{{.OUTPUT_DIR}}/sparse_refined/0"
  BRUSH_DIR: "{{.OUTPUT_DIR}}/brush"
  UNDISTORTED_IMAGES_DIR: "{{.OUTPUT_DIR}}/images"

  # COLMAP parameters
  MATCHER_TYPE: "{{.MATCHER_TYPE | default \"exhaustive_matcher\"}}"
  MODEL_TYPE: "{{.MODEL_TYPE | default \"3dgs\"}}"
  COLMAP_CAMERA_MODEL: "{{.COLMAP_CAMERA_MODEL | default \"OPENCV\"}}"

  # Brush parameters
  BRUSH_STEPS: "{{.BRUSH_STEPS | default 7000}}" # Increased to 7k for better texture settle
  BRUSH_EXPORT_EVERY: "{{.BRUSH_EXPORT_EVERY | default 1000}}"

  # Video extraction parameters
  FPS: "{{.FPS | default 10}}"

  # Database and output paths
  DATABASE_PATH: "{{.DISTORTED_DIR}}/database.db"

tasks:
  all:
    desc: "Run full pipeline to training"
    cmds:
      - task: brush-training

  extract-video:
    desc: "Extract frames from video file"
    status:
      - "test -z '{{.VIDEO}}' || [ $(ls -1 {{.IMAGE_PATH}}/*.png 2>/dev/null | wc -l) -gt 0 ]"
    cmds:
      - mkdir -p "{{.IMAGE_PATH}}"
      - ffmpeg -i "{{.VIDEO}}" -vf "fps={{.FPS}}" "{{.IMAGE_PATH}}/frame%04d.png"

  feature-extraction:
    desc: "Extract features using OPENCV model for Pixel 10"
    deps: [extract-video]
    generates: ["{{.DATABASE_PATH}}"]
    cmds:
      - mkdir -p "{{.DISTORTED_DIR}}"
      - |
        colmap feature_extractor \
          --image_path "{{.IMAGE_PATH}}" \
          --database_path "{{.DATABASE_PATH}}" \
          --ImageReader.single_camera 1 \
          --ImageReader.camera_model "{{.COLMAP_CAMERA_MODEL}}"

  feature-matching:
    desc: "Match features"
    deps: [feature-extraction]
    sources: ["{{.DATABASE_PATH}}"]
    cmds:
      - colmap {{.MATCHER_TYPE}} --database_path "{{.DATABASE_PATH}}"

  mapping:
    desc: "Build initial sparse model"
    deps: [feature-matching]
    sources: ["{{.DATABASE_PATH}}"]
    generates: ["{{.SPARSE_ZERO_DIR}}/points3D.bin"]
    cmds:
      - mkdir -p "{{.SPARSE_DIR}}"
      - |
        glomap mapper \
          --database_path "{{.DATABASE_PATH}}" \
          --image_path "{{.IMAGE_PATH}}" \
          --output_path "{{.SPARSE_DIR}}"
      - |
        if [ -f "{{.SPARSE_DIR}}/cameras.bin" ]; then
          mkdir -p "{{.SPARSE_ZERO_DIR}}"
          mv "{{.SPARSE_DIR}}/"*.bin "{{.SPARSE_ZERO_DIR}}/"
        fi
  
  bundle-adjustment:
    desc: "Refine camera poses and distortion"
    deps: [mapping]
    sources: ["{{.SPARSE_ZERO_DIR}}/points3D.bin"]
    generates: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    cmds:
      - mkdir -p "{{.SPARSE_ZERO_REFINED_DIR}}"
      - |
        colmap bundle_adjuster \
          --input_path "{{.SPARSE_ZERO_DIR}}" \
          --output_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --BundleAdjustment.refine_focal_length 1 \
          --BundleAdjustment.refine_extra_params 1 \
          --BundleAdjustment.refine_extrinsics 1
          
  ply-model:
    desc: "Convert refined model to PLY for seeding"
    deps: [bundle-adjustment]
    sources: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    generates: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.ply"]
    cmds:
      - |
        colmap model_converter \
          --input_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --output_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --output_type PLY

  undistorted-dataset:
    desc: "Create PINHOLE dataset from refined OPENCV params"
    deps: [bundle-adjustment]
    sources: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    generates: ["{{.UNDISTORTED_IMAGES_DIR}}/frame0001.png"]
    if: "test \"{{.MODEL_TYPE}}\" = \"3dgs\""
    cmds:
      - mkdir -p "{{.UNDISTORTED_IMAGES_DIR}}"
      - |
        colmap image_undistorter \
          --image_path "{{.IMAGE_PATH}}" \
          --input_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --output_path "{{.OUTPUT_DIR}}" \
          --output_type COLMAP

  brush-training:
    desc: "Train final Gaussian Splat"
    deps: [ply-model, undistorted-dataset]
    cmds:
      - mkdir -p "{{.BRUSH_DIR}}"
      - |
        brush_app \
          --total-steps {{.BRUSH_STEPS}} \
          --export-every {{.BRUSH_EXPORT_EVERY}} \
          --export-path "{{.BRUSH_DIR}}" \
          "{{.OUTPUT_DIR}}"

  clean:
    desc: "Remove generated directories"
    cmds:
      - rm -rf "{{.OUTPUT_DIR}}"
