version: '3'

vars:
  # Input/Output directories
  IMAGE_PATH: "{{if .IMAGE_PATH}}{{.IMAGE_PATH}}{{else}}{{.ROOT_DIR}}/frames{{end}}"
  VIDEO: "{{.VIDEO}}"
  # PARENT_DIR: absolute path to directory containing VIDEO or IMAGE_PATH
  PARENT_DIR: "{{if .VIDEO}}{{dir .VIDEO}}{{else}}{{dir .IMAGE_PATH}}{{end}}"
  OUTPUT_DIR: "{{.PARENT_DIR}}/gaussian-splat-generation"
  DISTORTED_DIR: "{{.OUTPUT_DIR}}/distorted"
  SPARSE_DIR: "{{.OUTPUT_DIR}}/sparse_initial" # Renamed to avoid collision with undistorted output
  SPARSE_ZERO_DIR: "{{.SPARSE_DIR}}/0"
  SPARSE_ZERO_REFINED_DIR: "{{.OUTPUT_DIR}}/sparse_refined/0"
  BRUSH_DIR: "{{.OUTPUT_DIR}}/brush"
  UNDISTORTED_IMAGES_DIR: "{{.OUTPUT_DIR}}/images"

  # COLMAP parameters
  MATCHER_TYPE: "{{.MATCHER_TYPE | default \"exhaustive_matcher\"}}"
  MODEL_TYPE: "{{.MODEL_TYPE | default \"3dgs\"}}"
  COLMAP_CAMERA_MODEL: "{{.COLMAP_CAMERA_MODEL | default \"OPENCV\"}}"

  # Brush parameters
  BRUSH_STEPS: "{{.BRUSH_STEPS | default 7000}}" # Increased to 7k for better texture settle
  BRUSH_EXPORT_EVERY: "{{.BRUSH_EXPORT_EVERY | default 1000}}"

  # Video extraction parameters
  FPS: "{{.FPS | default 10}}"

  # Database and output paths
  DATABASE_PATH: "{{.DISTORTED_DIR}}/database.db"
  
  MATCH_MARKER: "{{.DISTORTED_DIR}}/matching_done.marker"
  FEATURE_EXTRACTION_MARKER: "{{.DISTORTED_DIR}}/feature_extraction_done.marker"

tasks:
  check-input:
    desc: "Validate that either VIDEO or IMAGE_PATH is provided"
    silent: true
    cmds:
      - |
        if [ -z "{{.VIDEO}}" ] && [ -z "{{.IMAGE_PATH}}" ]; then
          echo "ERROR: Either VIDEO or IMAGE_PATH must be provided"
          echo "Usage: task extract-video VIDEO=/path/to/video.mp4"
          echo "   or: task feature-extraction IMAGE_PATH=/path/to/images"
          exit 1
        fi
        echo "✓ Input validation passed"

  default:
    desc: "Display help information and customizable variables"
    silent: true
    cmds:
      - task: check-input
      - |
        cat << 'EOF'

        ╔════════════════════════════════════════════════════════════════════════════╗
        ║                   COLMAP PIPELINE - Available Variables                    ║
        ╚════════════════════════════════════════════════════════════════════════════╝

        INPUT/OUTPUT VARIABLES (Required either one or the other):
          VIDEO                   Path to video file for frame extraction.
                                  Frames will be extracted to IMAGE_PATH directory ({{.IMAGE_PATH}})
                                  Current: {{.VIDEO}}
          IMAGE_PATH              Path to images directory
                                  Current: {{.IMAGE_PATH}}

        VIDEO EXTRACTION OPTIONS:
          FPS                     Frames per second for video extraction
                                  Current: {{.FPS}}

        COLMAP PROCESSING OPTIONS:
          MATCHER_TYPE            Type of feature matcher
                                  Options: sequential_matcher, exhaustive_matcher
                                  Current: {{.MATCHER_TYPE}}
          MODEL_TYPE              Model type for reconstruction
                                  Options: 3dgs, nerfstudio
                                  Current: {{.MODEL_TYPE}}
          COLMAP_CAMERA_MODEL     Camera model for feature extraction: https://colmap.github.io/cameras.html
                                  Current: {{.COLMAP_CAMERA_MODEL}}

        BRUSH TRAINING OPTIONS:
          BRUSH_STEPS             Total training steps for brush
                                  Current: {{.BRUSH_STEPS}}
          BRUSH_EXPORT_EVERY      Export model every N steps
                                  Current: {{.BRUSH_EXPORT_EVERY}}
                                  
        EOF
        
      - '{{.TASK_EXE}} --list --taskfile "{{.TASKFILE}}" --dir "{{.ROOT_DIR}}"'

  print-dirs:
    desc: "Print all directory paths for debugging"
    silent: true
    cmds:
      - |
        cat << 'EOF'

        ╔════════════════════════════════════════════════════════════════════════════╗
        ║                      DIRECTORY PATHS - DEBUG INFO                          ║
        ╚════════════════════════════════════════════════════════════════════════════╝

        DIRECTORY VARIABLES:
          PARENT_DIR:              {{.PARENT_DIR}}
          IMAGE_PATH:              {{.IMAGE_PATH}}
          DISTORTED_DIR:           {{.DISTORTED_DIR}}
          SPARSE_DIR:              {{.SPARSE_DIR}}
          SPARSE_ZERO_DIR:         {{.SPARSE_ZERO_DIR}}
          BRUSH_DIR:               {{.BRUSH_DIR}}
          UNDISTORTED_IMAGES_DIR:  {{.UNDISTORTED_IMAGES_DIR}}

        FILE PATHS:
          DATABASE_PATH:           {{.DATABASE_PATH}}

        OTHER VARIABLES:
          VIDEO:                   {{.VIDEO}}
          FPS:                     {{.FPS}}
          MATCHER_TYPE:            {{.MATCHER_TYPE}}
          MODEL_TYPE:              {{.MODEL_TYPE}}
          COLMAP_CAMERA_MODEL:     {{.COLMAP_CAMERA_MODEL}}
          BRUSH_STEPS:             {{.BRUSH_STEPS}}
          BRUSH_EXPORT_EVERY:      {{.BRUSH_EXPORT_EVERY}}

        EOF

  all:
    desc: "Run full pipeline to training"
    cmds:
      - task: brush-training

  extract-video:
    desc: "Extract frames from video file"
    deps: [check-input]
    status:
      - "test -z '{{.VIDEO}}' || [ $(ls -1 {{.IMAGE_PATH}}/*.png 2>/dev/null | wc -l) -gt 0 ]"
    cmds:
      - mkdir -p "{{.IMAGE_PATH}}"
      - |
        if [ -n "{{.VIDEO}}" ]; then
          ffmpeg -i "{{.VIDEO}}" -vf "fps={{.FPS}}" "{{.IMAGE_PATH}}/frame%04d.png"
        fi

  feature-extraction:
    desc: "Extract features using OPENCV model for Pixel 10"
    deps: [check-input, extract-video]
    sources:
      - "{{.IMAGE_PATH}}/**/*"
    generates: ["{{.DATABASE_PATH}}"]
    cmds:
      - mkdir -p "{{.DISTORTED_DIR}}"
      - |
        colmap feature_extractor \
          --image_path "{{.IMAGE_PATH}}" \
          --database_path "{{.DATABASE_PATH}}" \
          --ImageReader.single_camera 1 \
          --ImageReader.camera_model "{{.COLMAP_CAMERA_MODEL}}"
      - touch "{{.FEATURE_EXTRACTION_MARKER}}"

  feature-matching:
    desc: "Match features"
    deps: [feature-extraction]
    sources: ["{{.FEATURE_EXTRACTION_MARKER}}"]
    generates: ["{{.MATCH_MARKER}}"]
    cmds:
      - colmap {{.MATCHER_TYPE}} --database_path "{{.DATABASE_PATH}}"
      - touch "{{.MATCH_MARKER}}"

  mapping:
    desc: "Build initial sparse model"
    deps: [feature-matching]
    sources:
      - "{{.MATCH_MARKER}}"
      - "{{.IMAGE_PATH}}/**/*"
    generates: ["{{.SPARSE_ZERO_DIR}}/points3D.bin"]
    cmds:
      - mkdir -p "{{.SPARSE_DIR}}"
      - mkdir -p "{{.SPARSE_ZERO_DIR}}"
      - |
        glomap mapper \
          --database_path "{{.DATABASE_PATH}}" \
          --image_path "{{.IMAGE_PATH}}" \
          --output_path "{{.SPARSE_DIR}}"
      - |
        if [ -f "{{.SPARSE_DIR}}/cameras.bin" ]; then
          mv "{{.SPARSE_DIR}}/"*.bin "{{.SPARSE_ZERO_DIR}}/"
        fi
  
  bundle-adjustment:
    desc: "Refine camera poses and distortion"
    deps: [mapping]
    sources: ["{{.SPARSE_ZERO_DIR}}/points3D.bin"]
    generates: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    cmds:
      - mkdir -p "{{.SPARSE_ZERO_REFINED_DIR}}"
      - |
        colmap bundle_adjuster \
          --input_path "{{.SPARSE_ZERO_DIR}}" \
          --output_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --BundleAdjustment.refine_focal_length 1 \
          --BundleAdjustment.refine_extra_params 1 \
          --BundleAdjustment.refine_principal_point 0
          
  ply-model:
    desc: "Convert refined model to PLY for seeding"
    deps: [bundle-adjustment]
    sources: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    generates: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.ply"]
    cmds:
      - |
        colmap model_converter \
          --input_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --output_path "{{.SPARSE_ZERO_REFINED_DIR}}/points3D.ply" \
          --output_type PLY

  undistorted-dataset:
    desc: "Create PINHOLE dataset from refined OPENCV params"
    deps: [bundle-adjustment]
    sources: ["{{.SPARSE_ZERO_REFINED_DIR}}/points3D.bin"]
    generates: ["{{.UNDISTORTED_IMAGES_DIR}}/**/*"]
    if: "test \"{{.MODEL_TYPE}}\" = \"3dgs\""
    cmds:
      - mkdir -p "{{.UNDISTORTED_IMAGES_DIR}}"
      - |
        colmap image_undistorter \
          --image_path "{{.IMAGE_PATH}}" \
          --input_path "{{.SPARSE_ZERO_REFINED_DIR}}" \
          --output_path "{{.OUTPUT_DIR}}" \
          --output_type COLMAP

  brush-training:
    desc: "Train final Gaussian Splat"
    deps: [ply-model, undistorted-dataset]
    cmds:
      - mkdir -p "{{.BRUSH_DIR}}"
      - |
        brush_app \
          --total-steps {{.BRUSH_STEPS}} \
          --export-every {{.BRUSH_EXPORT_EVERY}} \
          --export-path "{{.BRUSH_DIR}}" \
          "{{.OUTPUT_DIR}}"

  clean:
    desc: "Remove generated directories"
    cmds:
      - rm -rf "{{.OUTPUT_DIR}}"
